#!/bin/bash
#################################################################
#
# Build script template for MapFL.
#
# See the build scripts in the "/build_examples" 
# folder for examples of what to insert here.
# Please do not edit this file, rather copy it to a new 
# file with your own configuration options inserted.
# If your configuration is unique, feel free to add it to the 
# /build_examples folder.
# Note that your build script must be launched from 
# this lowest level directory (not from the build_examples folder).
#
#################################################################
#################################################################
# Enter your compiler (e.g. gfortran, ifx, nvfortran, etc.).
#################################################################

FC="gfortran"

#################################################################
# Please set the location of the HDF5 include & library files. 
# Make sure the HDF5 LIBRARY is COMPILED with 
# the SAME COMPILER used here, and is in the run-time environment.
#################################################################

HDF5_INCLUDE_DIR="/usr/local/include/"
HDF5_LIB_DIR="/usr/local/lib/"

##################################################################
# Please set the HDF5 linker flags to match the installed version.
##################################################################

HDF5_LIB_FLAGS="-lhdf5_fortran -lhdf5_hl_fortran -lhdf5 -lhdf5_hl"

###########################################################################
# Please set the compile flags based on your compiler and hardware setup.
###########################################################################

FFLAGS="-O3 -march=native -fopenmp"

###########################################################################
#             END OF USER CONFIG.  DO NOT EDIT BELOW.                     #
###########################################################################
###########################################################################
###########################################################################
###########################################################################
###########################################################################
###########################################################################

MAPFL_HOME=$PWD

cX="\033[0m"
cR="\033[1;31m"
cB="\033[1;34m"
cG="\033[32m"
cC="\033[1;96m"
cM="\033[35m"
cY="\033[1;93m"
Bl="\033[1;5;96m"
echo="echo -e"

if [ -z "${OMP_NUM_THREADS}" ]
then
  ${echo} "${cR}WARNING!  OMP_NUM_THREADS is not set!${cX}"
  ${echo} "${cR}          This is used to run in parallel.${cX}"
  ${echo} "${cR}          If not set, all availble threads will be used.${cX}"
fi

${echo} "${cG}=== STARTING MAPFL BUILD ===${cX}"
${echo} "==> Entering src directory..."
pushd ${MAPFL_HOME}/src > /dev/null
${echo} "==> Removing old Makefile..."
if [ -e Makefile ]; then
  \rm Makefile
fi 
${echo} "==> Generating Makefile from Makefile.template..."
sed \
  -e "s#<FC>#${FC}#g" \
  -e "s#<FFLAGS>#${FFLAGS}#g" \
  -e "s#<HDF5_INCLUDE_DIR>#${HDF5_INCLUDE_DIR}#g" \
  -e "s#<HDF5_LIB_DIR>#${HDF5_LIB_DIR}#g" \
  -e "s#<HDF5_LIB_FLAGS>#${HDF5_LIB_FLAGS}#g" \
  Makefile.template > Makefile
${echo} "==> Compiling code..."
make clean 1>/dev/null 2>/dev/null ; make 1>build.log 2>build.err
if [ ! -e mapfl ]; then
  ${echo} "${cR}!!> ERROR!  mapfl executable not found.  Build most likely failed."
  ${echo} "            Contents of src/build.err:"
  cat build.err
  ${echo} "${cX}"
  exit 1
fi
$echo "==> Copying mapfl executable to: ${MAPFL_HOME}/bin/mapfl"
cp mapfl ${MAPFL_HOME}/bin/mapfl
${echo} "${cG}==> Build complete!${cX}"
${echo}      "    Please add the following to your shell startup (e.g. .bashrc, .profile, etc.):"
${echo} "${cC}    export PATH=${MAPFL_HOME}/bin:\$PATH${cX}"

