FC = <FC>

ifeq ($(TARGET),)
  TARGET = mapfl
endif

FFLAGS = <FRTFLAGS> -I<HDF5_INCLUDE_DIR>

OBJS = psi_io.o mapfl.o

LDFLAGS = -L<HDF5_LIB_DIR> <HDF5_LIB_FLAGS>

all: $(OBJS)
	$(FC) $(FFLAGS) $(OBJS) $(LDFLAGS) -o mapfl
	rm *.o *.mod

install:
	mv mapfl ../bin/mapfl

clean:
	rm -f *.mod *.o *.so 2>/dev/null
	rm mapfl 2>/dev/null

psi_io.o: psi_io.f90
	$(FC) -c $(FFLAGS) $<

mapfl.o: mapfl.f
	$(FC) -c $(FFLAGS) $<

